version: '3.7'
services:
  ndt-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    networks:
      - ndt-bridge
    ports:
      - "443:4443"
      - "3001:3001"
      - "3002:3002"
      - "3010:3010"
      - "9090:9090"
    volumes:
      - .:/go/src/github.com/m-lab/ndt-server
      - ./certs:/certs
      - ./data:/data
      - ./html:/go/html
    user: root
    cap_drop:
      - ALL
    command: ["ndt-server",
      "-cert", "/certs/cert.pem",
      "-key", "/certs/key.pem",
      "-datadir", "/data",
      "-ndt7_addr", ":4443"]
networks:
    ndt-bridge:
        # use the bridge driver, but enable IPv6
        driver: bridge