version: '3.7'
services:
  ndt-server:
    build:
      context: .
      dockerfile: Dockerfile.local
    network_mode: host
    volumes:
      - ./certs:/certs
      - ./datadir:/datadir
      - ./html:/html
    cap_drop:
      - ALL
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
    command: [
      "./ndt-server",
      "-cert", "/certs/cert.pem",
      "-key", "/certs/key.pem",
      "-datadir", "/datadir",
    ]
